### ISSUE TITLE
Error installing nel

### ISSUE THREAD

**Issue by CanLi1** [siddancha/10703-Navigation-Env#1]
Hi,

I'm trying to install the package on a linux server. 
When I run 
python setup.py install
I got the following error
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DMAJOR_VERSION=1 -DMINOR_VERSION=0 -I../.. -I../../deps -I/home/canl1/pyomo/local/lib/python2.7/site-packages/numpy/core/include -I/usr/include/python2.7 -c nel/simulator.cpp -o build/temp.linux-x86_64-2.7/nel/simulator.o -std=c++11 -stdlib=libc++ -Wall -Wpedantic -Ofast -DNDEBUG -fno-stack-protector -mtune=native -march=native
x86_64-linux-gnu-gcc: error: unrecognized command line option ‘-stdlib=libc++’

Do you guys have any idea how to fix it?
Thanks!

Best regards,
Can

**Comment by siddancha** [comment]
Could you please try removing '-stdlib=libc++' from line 8 in 'api/python/setup.py' and reinstalling?

**Comment by CanLi1** [comment]
I tried it already. It can install but when I tried to import nel in python. It says
    from nel import simulator_c
ImportError: cannot import name simulator_c

**Comment by siddancha** [comment]
Are you launching python from the 'api/python' folder while importing nel? If so, please try doing it from another folder. Eg. do a 'cd' first before launching python.

**Comment by CanLi1** [comment]
You are right. Thanks!
