### ISSUE TITLE
GCC doesn't support '-stdlib=libc++' flag

### ISSUE THREAD

**Issue by gokart23** [siddancha/10703-Navigation-Env#2]
*Issue*: The installation instructions running `python setup.py install` within an environment containign relatively recent versions of GCC, Clang or MSVC. However, GCC doesn't support flag `-stdlib=libc++`, which is specified by: https://github.com/siddancha/10703-Navigation-Env/blob/33c108249d9b83e3df9faedf20e799e50205e17f/api/python/setup.py#L8

*Environment:* GCC 8.2.1, Linux 4.18.10, Python 3.6.0

*Workaround:* For just the GCC setup, removing the flag seems to work. I'm not sure what the wider impact of this might be.

**Comment by siddancha** [comment]
That's the right solution -- removing the `stdlib=libc++` flag. Refer to #1 .
