### ISSUE TITLE
environment error in vision

### ISSUE THREAD

**Issue by Lilac-Lee** [siddancha/10703-Navigation-Env#4]
Hi,
As we proceed, we found that the vision content might be different from our understanding. You said that the vision content is the RGB images the agent seen. Which in our understanding, the diamond should be [0, 1, 0], tong is [1, 0, 0], and jelly beans [0, 0, 1]. However, by testing random walking, when the reward showed 100 (which indicate a diamond), the actual vision array is not [0, 1, 0], same for tong.
PS: when I mean the actual vision array, I mean the center value of the 11*11 matrix the agent perceived. (vision[5, 5, :])
Please give us some instructions at this point. Thank you.

**Comment by siddancha** [comment]
Since the agent (blue) is always at the center of the vision map, the color at (5, 5) is always going to be [0, 0, 1]. The agent will get a reward of 100 if the color at (5, 6) (the cell in front of the agent) is [0, 1, 0] and then the agent chooses the action 0.
